In [223]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [224]:
df = pd.read_csv("/content/drive/MyDrive/Pune/Datasets/startup_funding.csv")

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [226]:
df.sample(4)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
1489,1490,29/08/2016,Notion Press,Consumer Internet,Self-Publishing books platform,Chennai,Undisclosed HNI investors,Private Equity,"10,00,000",NaN
247,248,22/06/2018,WickedRide,Consumer Internet,Online Motorbike And Scooter Rental Platforms,Bengaluru,"Sequoia Capital, Accel Partners & Raghunandan ...",Private Equity,"91,00,000",NaN
232,233,10/06/2018,AyeFinance,Finance,Online Lending Platform,Gurugram,"CapitalG, SAIF Partners and LGT Impact Ventures",Private Equity,"2,15,00,000",NaN
2285,2286,30/11/2015,MoMagic,Mobile Application Developer,NaN,New Delhi,FIH Mobile Ltd,Private Equity,NaN,Strategic Investment

In [227]:
df['Remarks'].value_counts()

Remarks
Series A                             175
Series B                              63
Pre-Series A                          37
Series C                              28
Series D                              11
                                    ...
Pre Series-A                           1
QPrize Contest Winners                 1
pre-series A                           1
Personal Investment                    1
Strategic Funding, Minority stake      1
Name: count, Length: 72, dtype: int64

In [228]:
df.drop(columns =['Remarks'],inplace = True)

In [229]:
df.sample(3)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
414,415,24/01/2018,NeoGrowth Credit,Finance,Digital Lending,Mumbai,"LeapFrog Investments, Aspada Investment, Quona...",Private Equity,"4,70,00,000"
1798,1799,21/04/2016,mishTag,Consumer Internet,"Style, Fashion Discovery Mobile app",New Delhi,"M&Y Partners, SVG Media, Anthil Ventures & others",Seed Funding,NaN
2575,2576,02/07/2015,BankBazaar,Online Financial Services,NaN,Chennai,"Amazon, Fidelity Growth Partners, Mousse Partners",Private Equity,"6,00,00,000"

In [230]:
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [231]:
df.set_index('Sr No' , inplace = True)

In [232]:
df.shape

(3044, 8)

In [233]:
df

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...
3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [234]:
df.rename(columns= {
    'Date dd/mm/yyyy' : 'date',
    'Startup Name': 'startup',
    'Industry Vertical': 'vertical',
    'SubVertical' :'subvertical',
    'City  Location': 'city',
    'Investors Name' : 'investor',
    'InvestmentnType': 'round',
    'Amount in USD' :'amount'

},inplace =True)

In [235]:
df.head()

,date,startup,vertical,subvertical,city,investor,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [236]:
df['vertical'].value_counts().head(3)

vertical
Consumer Internet    941
Technology           478
eCommerce            186
Name: count, dtype: int64

In [237]:
df['subvertical'].value_counts().head(3)

subvertical
Online Lending Platform    11
Online Pharmacy            10
Food Delivery Platform      8
Name: count, dtype: int64

In [238]:
df.shape

(3044, 8)

In [239]:
#null values
df.isnull().sum()

date             0
startup          0
vertical       171
subvertical    936
city           180
investor        24
round            4
amount         960
dtype: int64

In [240]:
df['amount']

Sr No
1       20,00,00,000
2          80,48,394
3        1,83,58,860
4          30,00,000
5          18,00,000
            ...
3040       45,00,000
3041        8,25,000
3042       15,00,000
3043             NaN
3044        1,40,000
Name: amount, Length: 3044, dtype: object

In [241]:
df.isnull().sum()

date             0
startup          0
vertical       171
subvertical    936
city           180
investor        24
round            4
amount         960
dtype: int64

In [242]:
df['amount'] = df['amount'].str.replace(',','')

In [243]:
df['amount'] = df['amount'].str.replace('undisclosed','0')

In [244]:
df['amount'] = df['amount'].str.replace('unknown','0')

In [245]:
df['amount'] = df['amount'].str.replace('Undisclosed','0')

In [246]:
df['amount'] = df['amount'].str.replace('NAN','')

In [247]:
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

In [248]:
df['amount'] = df['amount'].fillna(df['amount'].mean()) #Filling the missing values with the mean

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   object
 1   startup      3044 non-null   object
 2   vertical     2873 non-null   object
 3   subvertical  2108 non-null   object
 4   city         2864 non-null   object
 5   investor     3020 non-null   object
 6   round        3040 non-null   object
 7   amount       3044 non-null   float64
dtypes: float64(1), object(7)
memory usage: 214.0+ KB

In [250]:
df.isnull().sum()

date             0
startup          0
vertical       171
subvertical    936
city           180
investor        24
round            4
amount           0
dtype: int64

In [251]:
def to_inr(dollar):
  inr = dollar * 84.36
  return inr/10000000

In [252]:
to_inr(400000)

3.3744

In [253]:
df['amount']= df['amount'].apply(to_inr)

In [254]:
df.head()

,date,startup,vertical,subvertical,city,investor,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1687.200000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,67.896252
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,154.875343
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,25.308000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,15.184800

In [255]:
df['date'] =  pd.to_datetime(df['date'],format='%d/%m/%Y' ,errors='coerce')

In [256]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3036 non-null   datetime64[ns]
 1   startup      3044 non-null   object
 2   vertical     2873 non-null   object
 3   subvertical  2108 non-null   object
 4   city         2864 non-null   object
 5   investor     3020 non-null   object
 6   round        3040 non-null   object
 7   amount       3044 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 214.0+ KB

In [257]:
df['date'].dt.month_name()

Sr No
1       January
2       January
3       January
4       January
5       January
         ...
3040    January
3041    January
3042    January
3043    January
3044    January
Name: date, Length: 3044, dtype: object

In [258]:
df['Month_name'] = df['date'].dt.month_name()

In [259]:
df.sample(5)

,date,startup,vertical,subvertical,city,investor,round,amount,Month_name
Sr No,,,,,,,,,
411,2018-01-22,Skillate,Technology,Artificial Intellegence,Bengaluru,"Incubate Fund India, Anuj Agrawal",Private Equity,154.949361,January
1468,2016-08-23,Octo.ai,Technology,Artificial Intelligence based marketing platform,New Delhi,"Outbox Ventures, Jaspreet Bindra, Arjun Malhot...",Seed Funding,1.687200,August
826,2017-05-16,Fynd,eCommerce,Fashion ECommerce Portal,Mumbai,Rocketship,Private Equity,4.218000,May
492,2017-11-10,Happily Unmarried,ECommerce,Online Gifting platform,Nw Delhi,Wipro Consumer Care,Private Equity,154.949361,November
2620,2015-07-15,Mobikon,Restaurant customer engagement platform,NaN,Pune,Jungle Ventures,Private Equity,19.402800,July

In [260]:
df.shape

(3044, 9)

In [261]:
df.isnull().sum()

date             8
startup          0
vertical       171
subvertical    936
city           180
investor        24
round            4
amount           0
Month_name       8
dtype: int64

In [262]:
df = df.dropna(subset = ['date','vertical','city','investor','round','Month_name'])

In [263]:
df.shape

(2830, 9)

In [276]:
df.isnull().sum()

date           0
startup        0
vertical       0
subvertical    0
city           0
investor       0
round          0
amount         0
Month_name     0
dtype: int64

In [ ]:
df['subvertical'] =df['subvertical'].fillna('Unkown')

#EDA

In [ ]:
df.sample(10)

In [ ]:
#Recent 5 investemnet from the investors
df[df['investor'] == 'Ratan Tata']

In [295]:
df[df['investor'].str.contains('Ratan Tata')][['date','startup','vertical','city','round','amount','investor']]

,date,startup,vertical,city,round,amount,investor
Sr No,,,,,,,
348,2018-03-27,The Print,Media,Delhi,Seed / Angel Funding,4.513260,Ratan Tata
839,2017-05-23,The Print,Consumer Internet,New Delhi,Seed Funding,154.949361,"Ratan Tata, Nandan Nilekani, Uday Kotak, Vijay..."
1267,2016-10-04,GOQii,Consumer Internet,Mumbai,Private Equity,154.949361,Ratan Tata
1368,2016-09-13,IdeaChakki,Consumer Internet,Delhi,Seed Funding,154.949361,Ratan Tata
1591,2016-06-10,Kyazoonga,eCommerce,Mumbai,Seed Funding,154.949361,Ratan Tata
1595,2016-06-10,MadRat Games,Technology,Bengaluru,Seed Funding,154.949361,"Ratan Tata, Bhavish Aggarwal, Ankit Bhati, Bin..."
1673,2016-05-04,Lenskart,eCommerce,New Delhi,Private Equity,506.160000,"International Finance Corp, TPG Growth, Adveq ..."
1718,2016-05-19,Niki.ai,Technology,Bengaluru,Private Equity,154.949361,Ratan Tata
1789,2016-04-19,LensKart,eCommerce,New Delhi,Private Equity,154.949361,Ratan Tata
1927,2016-02-08,Moglix,Ecommerce,New Delhi,Private Equity,154.949361,Ratan Tata
1934,2016-02-08,Invictus Oncology,Healthcare,New Delhi,Private Equity,154.949361,Ratan Tata
1953,2016-02-15,Snapbizz,Technology,Bengaluru,Private Equity,154.949361,Ratan Tata
1969,2016-02-17,Bollant Industries,Technology,Hyderabad,Private Equity,154.949361,Ratan Tata
2002,2016-02-29,Nestaway,Consumer Internet,Bengaluru,Private Equity,154.949361,Ratan Tata
2007,2016-01-04,DogSpot,ECommerce,Gurgaon,Seed Funding,154.949361,Ratan Tata
2015,2016-01-06,Tracxn,BFSI,Bengaluru,Seed Funding,154.949361,Ratan Tata
2061,2016-01-19,Cashkaro,Consumer Internet,Gurgaon,Private Equity,154.949361,Ratan Tata
2073,2016-01-21,FirstCry,ECommerce,Pune,Private Equity,154.949361,Ratan Tata
2090,2016-01-27,Teabox.com,ECommerce,Siliguri,Private Equity,154.949361,Ratan Tata
2152,2015-12-11,UrbanClap,Hyperlocal On-Demand Household Services platform,Gurgaon,Private Equity,154.949361,Ratan Tata
2201,2015-11-03,Sabse,WiFi \xe2\x80\x93 first Cloud communication pl...,Mumbai,Private Equity,154.949361,Ratan Tata
2269,2015-11-24,Crayon Data,Big Data Analytics Platform,Chennai/ Singapore,Private Equity,154.949361,Ratan Tata
2387,2015-09-02,HolaChef,Food Delivery Platform,Mumbai,Private Equity,154.949361,Ratan Tata
2526,2015-08-17,YourStory,Startup Focused Online Publisher,Mumbai,Seed Funding,154.949361,"Ratan Tata, Vani Kola, T V Mohandas Pai, Karth..."
2568,2015-08-31,Infinite Analytics,Big Data & predictive Analysis Platform,Mumbai,Private Equity,154.949361,"Ratan Tata, Nikhil Vora & others"
2574,2015-07-01,Ola Cabs,Cab rental Mobile app,Bengaluru,Private Equity,154.949361,Ratan Tata
2597,2015-07-08,Ampere,Electric Scooter manufacturer,Coimbatore,Seed Funding,154.949361,Ratan Tata
2601,2015-07-08,Lybrate,Healthcare Mobile App,New Delhi,Private Equity,86.047200,"Tiger Global Management, Ratan Tata, Nexus Ven..."
2686,2015-06-03,KAARYAH,Women Lifestyle Marketplace,Gurgaon,Seed Funding,154.949361,Ratan Tata

In [ ]:
#Which sub sector had received the highest funding  (top 5)
df.groupby('subvertical')['amount'].sum().sort_values(ascending = False).head(3)

In [282]:
#Average Funding
df['amount'].mean()

157.52063590785806

In [288]:
df['city'] = df['city'].str.replace('Bangalore','Bengaluru')

<ipython-input-288-8c77cb498006>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = df['city'].str.replace('Bangalore','Bengaluru')

In [289]:
#Which city has received the highest funding ?
df.groupby('city')['amount'].sum().sort_values(ascending = False).head(3)

city
Bengaluru    195497.963111
Mumbai        61679.830940
New Delhi     53349.188192
Name: amount, dtype: float64

In [301]:
#Recent 5 investemnet from the investors IDG Ventures with respect to city and amount spent
df[df['investor'].str.contains('IDG Ventures')]

,date,startup,vertical,subvertical,city,investor,round,amount,Month_name
Sr No,,,,,,,,,
102,2019-04-13,Tripoto,Social Media,Travel,New Delhi,"Orchid India, Hornbill Orchid India Fund, Chir...",Series B,30.296840,April
223,2018-07-30,Cure Fit,Consumer Internet,Health and fitness Platform,Bengaluru,"IDG Ventures, Accel Partners, Kalaari Capital ...",Private Equity,1012.320000,July
259,2018-05-02,Bizongo,Consumer Internet,Aggregator For Packaging Material,Mumbai,"B Capital, International Finance Corporation (...",Private Equity,185.592000,May
310,2018-04-26,POPxo,Technology,Women Focussed Digital Media Platform,Delhi,"Neoplux, OPPO, IDG Ventures India, Kalaari Cap...",Private Equity,46.398000,April
439,2017-12-07,eShakti,Ecommerce,"""Women\\'s Fashion Clothing Online Platform""",Chennai,IDG Ventures,Debt Funding,19.402800,December
478,2017-11-04,Hevo Data,Technology,Real time data analytics & reporting,Bengaluru,IDG Ventures India,Private Equity,8.436000,November
479,2017-11-06,Smart Karma,Technology,Financial Technology Research Platform,Bengaluru,IDG Ventures India,Private Equity,154.949361,November
490,2017-11-09,Mobiliz AR,Technology,Augmented Reality based Tech platform,Bengaluru,"IDG Ventures, IDFC-Parampara Fund",Private Equity,154.949361,November
505,2017-11-21,Heckyl,Technology,Big Data Analytics Platform,Mumbai,"Notion Capital, IDG Ventures",Private Equity,22.777200,November
528,2017-10-05,Little Black Book,Consumer Internet,Local Recommendations and Discoveries Platform,New Delhi,"Blume Ventures, IDG Ventures & Indian Angel Ne...",Private Equity,8.436000,October
660,2017-08-21,Uniphore,Technology,speech recognition startup,Chennai,IDG Ventures,Private Equity,57.364800,August
673,2017-08-29,CureFit,Consumer Internet,End to End health and wellness platform.,Bengaluru,"Accel Partners, IDG Ventures, Kalaari Capital,...",Private Equity,210.900000,August
699,2017-07-17,Vayana,Technology,Enterprise Banking Solutions,Pune,"IDG Ventures India Advisors, Jungle Ventures",Private Equity,33.744000,July
948,2017-03-07,Blowhorn,Consumer Internet,Intra-City Logistics provider,Bengaluru,"IDG Ventures India, Michael & Susan Dell Found...",Private Equity,30.791400,March
962,2017-03-16,mPaani,Consumer Internet,Loyalty rewards app,Mumbai,"IDG Ventures, Blume Ventures, Saha Fund,",Private Equity,11.388600,March
964,2017-03-16,POPxo,Consumer Internet,Digital Media publication for women,New Delhi,"GREE Ventures, Kalaari Capital and IDG Venture...",Private Equity,26.151600,March
1012,2017-02-13,Sigtuple,Technology,Medical Automation platform,Bengaluru,"Accel Partners, IDG Ventures, Endiya Partners,...",Private Equity,48.928800,February
1061,2017-01-12,Hansel.io,Consumer Internet,Real-time Mobile App Management Platform,Bengaluru,"IDG Ventures, Endiya Partners",Private Equity,11.388600,January
1202,2016-11-05,Bizongo,eCommerce,Packaging Material Marketplace,Mumbai,"IDG Ventures, Accel Partners",Private Equity,25.308000,November
1211,2016-11-14,Active.ai,Technology,Banking & Fintech Platform,Singapore,"Kalaari Capital, IDG Ventures India",Private Equity,25.308000,November
1215,2016-11-15,PlaySimple,Technology,Mobile Gaming portal,Bengaluru,"SAIF Partners, IDG Ventures India",Private Equity,33.744000,November
1234,2016-11-23,Infisecure,Technology,Bot Protection Solutions,Mumbai,"IDG Ventures, Axilor Ventures",Seed Funding,5.061600,November
1263,2016-10-03,Uniphore,Technology,Speech Recognition Solutions,Chennai,"IDG Ventures, Indian Angel Network (IAN), Your...",Private Equity,16.872000,October
1395,2016-09-23,\\xc2\\xa0CloudCherry,Technology,CRM SAAS Platform,Chennai,"Vertex Ventures, Cisco Ventures, IDG Ventures",Private Equity,50.616000,September
1498,2016-08-31,Flyrobe,eCommerce,Online fashion rental platform,Mumbai,"IDG Ventures, Sequoia Capital, GREE Ventures",Private Equity,44.710800,August
1506,2016-07-04,Curefit,Consumer Internet,Online Preventive Healthcare Platform,Bengaluru,"Accel Partners, IDG Ventures, Kalaari Capital",Private Equity,126.540000,July
1536,2016-07-13,RentMojo,Consumer Internet,Online Furniture Renting Platform,Bengaluru,"Accel Partners, IDG Ventures India",Private Equity,42.180000,July
1673,2016-05-04,Lenskart,eCommerce,Eyewear & Accessories etailer,New Delhi,"International Finance Corp, TPG Growth, Adveq ...",Private Equity,506.160000,May
1681,2016-05-05,Unbxd,Technology,eCommerce product discovery software,New Delhi,"IDG Ventures, Inventus Capital, Indian Angel N...",Private Equity,154.949361,May
1689,2016-05-10,HealthifyMe,Consumer Internet,Health & Fitness App,Bengaluru,"IDG Ventures India, Inventus Capital, Blume Ve...",Private Equity,50.616000,May
1933,2016-02-08,Xpressbees,ECommerce,ECommerce Logistics solutions,Pune,"SAIF Partners, IDG Ventures India, Vertex Vent...",Private Equity,105.450000,February
1950,2016-02-15,Aasaanjobs,Consumer Internet,Online Recruitment Marketplace,Mumbai,"Aspada Advisors, IDG Ventures,\\xc2\\xa0 Inven...",Private Equity,42.180000,February
2199,2015-11-02,CityFlo,Bus Aggregation and rental mobile app,Unkown,Mumbai,IDG Ventures,Seed Funding,6.327000,November
2216,2015-11-06,POPxo.com,Online content platform for women,Unkown,New Delhi,"IDG Ventures India, Kalaari Capital, 500 Startups",Private Equity,16.872000,November
2264,2015-11-23,RentoMojo,"Online Furniture, Home Appliances Rental Platform",Unkown,Bengaluru,"IDG Ventures India,\\xc2\\xa0 Accel Partners I...",Private Equity,16.872000,November
2276,2015-11-26,Pluss,Hyperlocal healthcare product Delivery Service...,Unkown,Gurgaon,"IDG Ventures, M & S partners, Powerhouse Ventu...",Private Equity,8.436000,November
2329,2015-10-12,Tripoto,global community for travellers,Unkown,New Delhi,"500 Startups, IDG Ventures & Advantedge fund, ...",Private Equity,154.949361,October
2521,2015-08-13,Agrostar,Mobile Commerce for Farmers,Unkown,Pune,IDG Ventures,Private Equity,33.744000,August
2571,2015-07-01,Cloudcherry Analytics,CRM / Analytics platform,Unkown,Chennai,"The Chennai Angels, IDG Ventures India",Seed Funding,8.436000,July
2635,2015-07-23,iCrushiFlush,Casual Dating App,Unkown,Mumbai,IDG Ventures India,Seed Funding,154.949361,July
2652,2015-07-29,Zimmber,Hyperlocal Handyman Services,Unkown,Mumbai,"IDG Ventures India, Omidyar Network, Sherpalo ...",Private Equity,16.872000,July
2742,2015-06-26,CreditMantri,Credit Management Services,Unkown,Chennai,"IDG Ventures India, Elevar Equity, Accion Vent...",Private Equity,21.090000,June
2761,2015-05-05,Fintellix,Banking Analytics Platform,Unkown,Bengaluru,"IDG Ventures, Sequoia Capital",Private Equity,126.540000,May
2765,2015-05-07,Uniphore,Speech Recognition Solutions,Unkown,Chennai,"IDG Ventures, Kris Gopalakrishnan",Private Equity,154.949361,May
2819,2015-04-08,FirstCry.com,eCommerce,Unkown,Pune,"Silicon Valley Ventures, NEA Ventures, Valiant...",Private Equity,84.360000,April

In [ ]:
#plot a graph to show how the investment in changing over the period of time for IDG Ventures

In [ ]:
#number of unique startup ?

In [ ]:
#plot a graph to